const assert = require('node:assert/strict');
const { loadTS } = require('../scripts/sincronizar_control.cjs');
const math = loadTS('lib/control-math.ts');
const metric = { key: 'n', format: 'count', label: 'Total' };
assert.deepEqual(math.previousPeriod({from:'2026-09-02',to:'2026-09-08'}), {from:'2026-08-26',to:'2026-09-01'});
assert.deepEqual(math.previousPeriod({from:'2026-09-08T12:00',to:'2026-09-08T12:59'}), {from:'2026-09-08T11:00',to:'2026-09-08T11:59'});
assert.deepEqual(math.previousPeriod({from:'',to:''}), {from:'',to:''});
const rows = [{fecha:'2026-09-01',n:0,tenant:'A'},{fecha:'2026-09-03',n:20,tenant:'B'}];
const points = math.series(rows,{from:'2026-09-01',to:'2026-09-03'},metric);
assert.deepEqual(points.map(p=>p.value),[0,null,20]);
assert.deepEqual(math.indexed(points).map(p=>p.value),[0,null,100]);
assert.equal(math.selectPeriod(rows,{from:'2026-09-01',to:'2026-09-03'},{tenant:'A'}).length,1);
assert.equal(math.delta(10,null).value,null);
assert.equal(math.delta(10,0).value,null);
assert.equal(math.delta(15,10).value,50);
assert.equal(math.delta(75,70,true).value,5);
assert.equal(math.sourceAge('2026-09-08T12:00:00',Date.parse('2026-09-08T15:05:00Z')),5);
async function main() {
  const store = loadTS('lib/github-store.ts');
  const reads = [];
  store.listDashboards = async () => [{user:'a',project:'one'},{user:'b',project:'two'}];
  store.getDashboard = async (u,p) => { reads.push(`${u}/${p}`); return {}; };
  const {readControl} = loadTS('lib/control-store.ts');
  const result = await readControl({u:'test',a:['a/one'],admin:false,t:0,s:''});
  assert.deepEqual(reads,['a/one']);
  assert.equal(result.projects.length,1);
  store.getDashboard = async (u) => { if(u==='a') throw new Error('private details'); return {}; };
  const partial = await readControl({u:'admin',a:[],admin:true,t:0,s:''});
  assert.equal(partial.projects.length,2);
  assert.ok(partial.projects[0].error);
  assert.equal(partial.projects[1].error,null);
  assert.ok(!JSON.stringify(partial).includes('private details'));
  const {GET} = loadTS('app/api/control/route.ts');
  const response = await GET({cookies:{get:()=>undefined}});
  assert.equal(response.status,401);
  assert.equal(response.headers.get('cache-control'),'private, no-store');
  console.log('Control: periodos, huecos, deltas, zona horaria, permisos y fallos parciales OK');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
